name: Check correct build before merging

on:
  pull_request:
    types: [opened, edited, reopened]
  push: 

concurrency: 
  group: Build for StandaloneWindows64 - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} - ${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}